export const CHANGE_BACKGROUNDCOLOR = 'CHANGE_BACKGROUNDCOLOR';
export const CHANGE_TEXTCOLOR = 'CHANGE_TEXTCOLOR';
export const CHANGE_SHOWIMAGE = 'CHANGE_SHOWIMAGE';
export const CHANGE_SHOWFACE = 'CHANGE_SHOWFACE';
export const USE_DEFAULT = 'USE_DEFAULT';

